# Generated by Django 4.1.1 on 2025-05-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_last_sales_date_alter_inventory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='last_sales_date',
            field=models.DateField(auto_now=True),
        ),
    ]
