# Generated by Django 4.1.1 on 2025-05-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_last_sales_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.CharField(blank=True, help_text='Kategoriya nomini kiriting', max_length=100, null=True),
        ),
    ]
